### ISSUE TITLE
Wrong brackets formatting

### ISSUE THREAD

**Issue by mad-rain** [Konash/arabic-support-unity#22]
Hi!

There is a problem with brackets formatting. Script reverses them when this is not needed.

(سربازخانه (0/18

**Comment by Konash** [comment]
Hi, 
The scripts reverses them because it assumes that what is between the brackets is arabic letters.

![image](https://user-images.githubusercontent.com/12271954/33409763-13885e2e-d54b-11e7-8541-f9c94172361c.png)

If you rather using numbers instead, I suggest you comment the part in the code when the brackets are flipped.

`if (lettersFinal[i] == '(')
					numberList.Add(')');
				else if (lettersFinal[i] == ')')
					numberList.Add('(');
				else if (lettersFinal[i] == '<')
					numberList.Add('>');
				else if (lettersFinal[i] == '>')
					numberList.Add('<');
				else if (lettersFinal[i] == '[')
					list.Add(']');
				else if (lettersFinal[i] == ']')
					list.Add('[');`
