### ISSUE TITLE
Order is wrong in mixed-language text

### ISSUE THREAD

**Issue by Nathipha** [Konash/arabic-support-unity#47]
I just downloaded the latest version of the asset for Unity 2021.1 and unfortunately there's a big problem with the order.

Example text (copied from google translate):

> This is a test. هذا اختبار. Another test!
(it's the wrong order in my actual text, apparently copying it/github changes it!)

Using `ArabicFixer.Fix()` on it results in this (doesn't matter if it's a 3D TMP text or a regular canvas/UI TMP one):

> Another test! .هذا اختبار This is a test.

As you can see, the English text is also swapped and with different test texts it even happens mid-sentence (wherever the Arabic part is).

Any idea how this can be fixed?

**Comment by Konash** [comment]
In theory, the output is correct because Arabic is a right to left
language.
As I'm reading this I'm seeing the order as:
1. This is a test.
2. .هذا اختبار
3. Another test!

The input however is not RTL.
I hope that clarifies.

**Comment by Nathipha** [comment]
Thanks for your reply! I see, so the asset basically turns everything into Arabic RTL, no matter the actual language used, and doesn't support mixed languages (that would require different directions), correct?

**Comment by Konash** [comment]
If we consider that, by using the Plugin, Arabic is the default language,
then we could say that it does support multiple languages on the same line.
But it won't work well if the any other language is the base.

To counter this, you can detect the Arabic part in your sentence, and apply
it sentence by sentence rather than word by word.
