### ISSUE TITLE
AlefMaksora is set to Yeh - causing Yeh to be used instead of AlefMaksora after running the Fix

### ISSUE THREAD

**Issue by havchr** [Konash/arabic-support-unity#49]
When we received our translation we had the character AlefMaksora 0x0649 in our characters.
This was then converted into isolated form through the mapping : 
		mapList.Add(new ArabicMapping((int)GeneralArabicLetters.AlefMagsora, (int)IsolatedArabicLetters.AlefMaksora));
but the isolated AlefMaksora was set to 
	AlefMaksora = 0xFBFC,
Which is the same as the 
	PersianYeh = 0xFBFC,
shouldn't it be set to
	AlefMaksora = 0xFEEF,
instead?

The result for us, was that our localization changed from AlefMaksora to Yeh and our font did not contain the perisan yeh-variants.
I am unsure what should be the correct behaviour here because I do not speak the language.

Thank you for the arabic support code, it is working very well, except this one issue we are having - best regards.

**Comment by albrrt** [comment]
Same issue here

Original Character: [0x0649](https://old.unicode-table.com/en/0649/)
Resulting Character: [0xFBFD](https://old.unicode-table.com/en/FBFD/)

The switch happens somewhere in the `internal static string FixLine(string str)` method of the ArabicSupport.cs script because the character looks fine before the method call, but looks wrong in the returned string.

Example sentence:

Before Fix Line: يرجى عدم استخدام
After Fix Line: ماﺪﺨﺘﺳا مﺪﻋ ﯽﺟﺮﻳ

**Comment by Konash** [comment]
Hi. I did try the example supplied: يرجى عدم استخدام
It works alright. Perhaps it is something with the font used?
