### ISSUE TITLE
Wrong character

### ISSUE THREAD

**Issue by mertguner** [Konash/arabic-support-unity#8]
Hi
I writing (Settings)تنظیمات but result تﺎﻤیﻈﻨﺗ

**Comment by Konash** [comment]
Hi,

This is happening because you are using ى instead of ي. You cannot connect ى to something after it in Arabic.

Check the images below:

![image](https://cloud.githubusercontent.com/assets/12271954/24668900/58f510fa-1936-11e7-8d6f-e10417a53fc0.png)

![image](https://cloud.githubusercontent.com/assets/12271954/24668993/a6285814-1936-11e7-8fd2-d077475e0bf9.png)

**Comment by Konash** [comment]
That being said, let me know if this issue is relevant to you. You might be using Farsi, if it makes sense in your case please reopen the issue.
